language: ruby
rvm: 2.4.1
cache: bundler
script: bundle exec rake test
addons:
  postgresql: "9.4"
before_script:
  - sudo apt-get install postgresql-server-dev-9.4
  - psql -c 'create database pghero_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
